name: My First GitHub Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create virtual environment
        run: |
          python -m venv venv  # Create a virtual environment
          source venv/bin/activate  # Activate the virtual environment
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies

      - name: Run tests
        run: |
          source venv/bin/activate  # Activate the virtual environment
          python -m pytest  # Run the tests.

