name: Django CI Workflow

on:
  push:
    branches:
      - main  # Adjust this to your default branch if necessary
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13  # Use an appropriate version for your app
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: django_notes_db
        ports:
          - 5432:5432
        # Wait for the service to be ready
        options: >-
          --health-cmd "pg_isready -U postgres" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --verbose

      - name: Run migrations
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/django_notes_db  # Adjust according to your settings
        run: |
          python manage.py migrate

      - name: Run tests
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/django_notes_db  # Adjust according to your settings
        run: |
          python manage.py test --verbosity=2

